animals = ['donkeys', 'cows', 'monkeys', 'bird', 'bird']
print(animals)
w = animals.count('bird')
print(w)
animals.sort(reverse=True)
print(animals)
animals.sort(reverse=True)
# using sort with brackets empty sort the array in assending order
print(animals)
x = len(animals)
print(x)
animals.remove('cows')
print(animals)
animals.pop(0)
print(animals)
animals.append('lions')
print(animals)
animals.clear()
print(animals)